import{a as b,S as w,i as O}from"./assets/vendor-4d51048b.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const y of s.addedNodes)y.tagName==="LINK"&&y.rel==="modulepreload"&&i(y)}).observe(document,{childList:!0,subtree:!0});function a(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(t){if(t.ep)return;t.ep=!0;const s=a(t);fetch(t.href,s)}})();const m=function(e){const a=[];return e.forEach(i=>{a.push(`<li class="gallery-item">
            <a class="gallery-link" href="${i.largeImageURL}">
            <div class="wrapper">
            <img class="gallery-image" src="${i.webformatURL}" alt="${i.tags}">
            <div class="title-wrapper">
            <p class="title">Likes<span>${i.likes}</span></p>
            <p class="title">Views<span>${i.views}</span></p>
            <p class="title">Comments<span>${i.comments}</span></p>
            <p class="title">Downloads<span>${i.downloads}</span></p>
            </div>
            </div>
            </a>
            </li>`)}),a.join("")},L=15;async function v(o,e){console.log(e);const a=await b.get("https://pixabay.com/api/?",{params:{key:"43830110-6528f7a21182a7b65b70041af",q:`${o}`,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:L,page:e}});if(a.status===200)return a.data}const r=document.querySelector(".gallery-button"),d=document.querySelector(".gallery-list"),g=document.querySelector(".loader"),l=document.querySelector(".search-input"),u=document.querySelector(".message"),p=document.querySelector(".search-form");let n=1,f,h,c=new w(".gallery a",{overlayOpacity:.8,captionSelector:"img",captionDelay:250,captionPosition:"bottom",captionsData:"alt",className:"simple-lightbox"});p.addEventListener("submit",async o=>{if(o.preventDefault(),n=1,u.classList.add("is-hidden"),l.value.trim()===""){p.reset();return}else g.classList.remove("is-hidden"),d.innerHTML="",r.classList.add("is-hidden"),await v(l.value,n).then(e=>{console.log(e),h=Math.ceil(e.total/L),console.log(h),e.hits.length===0?(l.value="",O.show({id:null,class:".izi-toast",message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"#fff",messageSize:"14px",messageLineHeight:"",backgroundColor:"#EF4040",theme:"light",color:"",icon:"",iconText:"",iconColor:"",iconUrl:"",maxWidth:430,zindex:null,layout:1,balloon:!1,close:!0,closeOnEscape:!1,closeOnClick:!1,displayMode:0,position:"topRight",target:"",targetFirst:!0,timeout:3e3,rtl:!1,animateInside:!0,drag:!0,pauseOnHover:!0,resetOnHover:!1,progressBar:!0,progressBarColor:"",progressBarEasing:"linear",overlay:!1,overlayClose:!1,overlayColor:"rgba(0, 0, 0, 0.6)",transitionIn:"fadeInUp",transitionOut:"fadeOut",transitionInMobile:"fadeInUp",transitionOutMobile:"fadeOutDown",buttons:{},inputs:{},onOpening:function(){},onOpened:function(){},onClosing:function(){},onClosed:function(){}})):n===h?(r.classList.add("is-hidden"),p.reset(),d.insertAdjacentHTML("afterbegin",m(e.hits)),c.refresh(),c.on("open.simplelightbox"),u.classList.remove("is-hidden"),l.value=""):(u.classList.add("is-hidden"),d.insertAdjacentHTML("afterbegin",m(e.hits)),c.refresh(),c.on("open.simplelightbox"),r.classList.remove("is-hidden"),f=document.querySelector(".gallery-item").getBoundingClientRect().height,n=1)}).catch(e=>e.status);g.classList.add("is-hidden")});r.addEventListener("click",async()=>{g.classList.remove("is-hidden"),r.classList.add("is-hidden"),n+=1,window.scrollBy({top:f*2,left:0,behavior:"smooth"}),await v(l.value,n).then(o=>{n===h?(d.insertAdjacentHTML("beforeend",m(o.hits)),window.scrollBy({top:f*2,left:0,behavior:"smooth"}),u.classList.remove("is-hidden"),r.classList.add("is-hidden"),l.value="",p.reset()):(d.insertAdjacentHTML("beforeend",m(o.hits)),window.scrollBy({top:f*2,left:0,behavior:"smooth"}),c.refresh(),c.on("open.simplelightbox"),r.classList.remove("is-hidden"))}).catch(o=>{o.status}),g.classList.add("is-hidden")});
//# sourceMappingURL=commonHelpers.js.map
